
DROP TABLE IF EXISTS Laendercodes;

CREATE TABLE Laendercodes (
    id INTEGER PRIMARY KEY,
    Land TEXT NOT NULL, 
    ISO3166_alpha2 TEXT NOT NULL, 
    ISO3166_alpha3  TEXT,
    ISO3166_numerisch  TEXT NOT NULL, 
    IOC  TEXT, 
    Fips10 TEXT, 
    Kfz_Kennzeichen TEXT, 
    Domain TEXT
);

INSERT INTO Laendercodes (
    Land, 
    ISO3166_alpha2, 
    ISO3166_alpha3,
    ISO3166_numerisch, 
    IOC, 
    Fips10, 
    Kfz_Kennzeichen, 
    Domain
)
VALUES
('Afghanistan','AF','AFG','004','AFG','AF','AFG','.af'),
('Ägypten','EG','EGY','818','EGY','EG','ET','.eg'),
('Ålandinseln','AX','ALA','248','','','AX','.ax'),
('Albanien','AL','ALB','008','ALB','AL','AL','.al'),
('Algerien','DZ','DZA','012','ALG','AG','DZ','.dz'),
('Amerikanisch Samoa','AS','ASM','016','ASA','AQ','USA','.as'),
('Andorra','AD','AND','020','AND','AN','AND','.ad'),
('Angola','AO','AGO','024','ANG','AO','ANG','.ao'),
('Anguilla','AI','AIA','660','','AV','AXA','.ai'),
('Antarktis','AQ','ATA','010','','AY','','.aq'),
('Antigua und Barbuda','AG','ATG','028','ANT','AC','AG','.ag'),
('Äquatorialguinea','GQ','GNQ','226','GEQ','EK','GQ','.gq'),
('Argentinien','AR','ARG','032','ARG','AR','RA','.ar'),
('Armenien','AM','ARM','051','ARM','AM','AM','.am'),
('Aruba','AW','ABW','533','ARU','AA','ARU','.aw'),
('Aserbaidschan','AZ','AZE','031','AZE','AJ','AZ','.az'),
('Äthiopien','ET','ETH','231','ETH','ET','ETH','.et'),
('Australien','AU','AUS','036','AUS','AS','AUS','.au'),
('Bahamas','BS','BHS','044','BAH','BF','BS','.bs'),
('Bahrain','BH','BHR','048','BRN','BA','BRN','.bh'),
('Bangladesch','BD','BGD','050','BAN','BG','BD','.bd'),
('Barbados','BB','BRB','052','BAR','BB','BDS','.bb'),
('Belarus','BY','BLR','112','BLR','BO','BY','.by'),
('Belgien','BE','BEL','056','BEL','BE','B','.be'),
('Belize','BZ','BLZ','084','BIZ','BH','BZ','.bz'),
('Benin','BJ','BEN','204','BEN','BN','BJ','.bj'),
('Bermuda','BM','BMU','060','BER','BD','','.bm'),
('Bhutan','BT','BTN','064','BHU','BT','BHT','.bt'),
('Bolivien','BO','BOL','068','BOL','BL','BOL','.bo'),
('Bonaire, Sint Eustatius und Saba','BQ','BES','535','','','NL','.bq'),
('Bosnien und Herzegowina','BA','BIH','070','BIH','BK','BIH','.ba'),
('Botswana','BW','BWA','072','BOT','BC','RB','.bw'),
('Bouvetinsel','BV','BVT','074','','BV','','.bv'),
('Brasilien','BR','BRA','076','BRA','BR','BR','.br'),
('Britisches Territorium im Indischen Ozean','IO','IOT','086','','IO','','.io'),
('Brunei','BN','BRN','096','BRU','BX','BRU','.bn'),
('Bulgarien','BG','BGR','100','BUL','BU','BG','.bg'),
('Burkina Faso','BF','BFA','854','BUR','UV','BF','.bf'),
('Burundi','BI','BDI','108','BDI','BY','RU','.bi'),
('Chile','CL','CHL','152','CHI','CI','RCH','.cl'),
('China','CN','CHN','156','CHN','CH','CHN','.cn'),
('Cookinseln','CK','COK','184','COK','CW','','.ck'),
('Costa Rica','CR','CRI','188','CRC','CS','CR','.cr'),
('Curaçao','CW','CUW','531','','UC','','.cw'),
('Dänemark','DK','DNK','208','DEN','DA','DK','.dk'),
('Demokratische Republik Kongo','CD','COD','180','COD','CG','CGO','.cd'),
('Deutschland','DE','DEU','276','GER','GM','D','.de'),
('Dominica','DM','DMA','212','DMA','DO','WD','.dm'),
('Dominikanische Republik','DO','DOM','214','DOM','DR','DOM','.do'),
('Dschibuti','DJ','DJI','262','DJI','DJ','DJI','.dj'),
('Ecuador','EC','ECU','218','ECU','EC','EC','.ec'),
('El Salvador','SV','SLV','222','ESA','ES','ES','.sv'),
('Elfenbeinküste','CI','CIV','384','CIV','IV','CI','.ci'),
('Eritrea','ER','ERI','232','ERI','ER','ER','.er'),
('Estland','EE','EST','233','EST','EN','EST','.ee'),
('Eswatini','SZ','SWZ','748','SWZ','WZ','SD','.sz'),
('Falklandinseln','FK','FLK','238','','FK','','.fk'),
('Färöer-Inseln','FO','FRO','234','','FO','FO','.fo'),
('Fidschi','FJ','FJI','242','FIJ','FJ','FJI','.fj'),
('Finnland','FI','FIN','246','FIN','FI','FIN','.fi'),
('Frankreich','FR','FRA','250','FRA','FR','F','.fr'),
('Französisch-Guayana','GF','GUF','254','','FG','','.gf'),
('Französisch-Polynesien','PF','PYF','258','','FP','','.pf'),
('Französische Süd- und Antarktisgebiete','TF','ATF','260','','FS','','.tf'),
('Gabun','GA','GAB','266','GAB','GB','G','.ga'),
('Gambia','GM','GMB','270','GAM','GA','WAG','.gm'),
('Georgien','GE','GEO','268','GEO','GG','GE','.ge'),
('Ghana','GH','GHA','288','GHA','GH','GH','.gh'),
('Gibraltar','GI','GIB','292','','GI','GBZ','.gi'),
('Grenada','GD','GRD','308','GRN','GJ','WG','.gd'),
('Griechenland','GR','GRC','300','GRE','GR','GR','.gr'),
('Grönland','GL','GRL','304','','GL','KN','.gl'),
('Guadeloupe','GP','GLP','312','','GP','','.gp'),
('Guam','GU','GUM','316','GUM','GQ','','.gu'),
('Guatemala','GT','GTM','320','GUA','GT','GCA','.gt'),
('Guernsey','GG','GGY','831','','GK','GBG','.gg'),
('Guinea','GN','GIN','324','GUI','GV','RG','.gn'),
('Guinea-Bissau','GW','GNB','624','GBS','PU','GUB','.gw'),
('Guyana','GY','GUY','328','GUY','GY','GUY','.gy'),
('Haiti','HT','HTI','332','HAI','HA','RH','.ht'),
('Heard und McDonaldinseln','HM','HMD','334','','HM','','.hm'),
('Honduras','HN','HND','340','HON','HO','HN','.hn'),
('Hongkong','HK','HKG','344','HKG','HK','HK','.hk'),
('Indien','IN','IND','356','IND','IN','IND','.in'),
('Indonesien','ID','IDN','360','INA','ID','RI','.id'),
('Insel Man','IM','IMN','833','','','','.im'),
('Irak','IQ','IRQ','368','IRQ','IZ','IRQ','.iq'),
('Iran','IR','IRN','364','IRI','IR','IR','.ir'),
('Irland','IE','IRL','372','IRL','EI','IRL','.ie'),
('Island','IS','ISL','352','ISL','IC','IS','.is'),
('Israel','IL','ISR','376','ISR','IS','IL','.il'),
('Italien','IT','ITA','380','ITA','IT','I','.it'),
('Jamaika','JM','JAM','388','JAM','JM','JA','.jm'),
('Japan','JP','JPN','392','JPN','JA','J','.jp'),
('Jemen','YE','YEM','887','YEM','YM','YEM','.ye'),
('Jersey','JE','JEY','832','','JE','GBJ','.je'),
('Jordanien','JO','JOR','400','JOR','JO','JOR','.jo'),
('Jungferninseln [UK]','VG','VGB','092','IVB','VI','VG','.vg'),
('Jungferninseln [US]','VI','VIR','850','ISV','VQ','','.vi'),
('Kaimaninseln','KY','CYM','136','CAY','CJ','','.ky'),
('Kambodscha','KH','KHM','116','CAM','CB','K','.kh'),
('Kamerun','CM','CMR','120','CMR','CM','CAM','.cm'),
('Kanada','CA','CAN','124','CAN','CA','CDN','.ca'),
('Kap Verde','CV','CPV','132','CPV','CV','CV','.cv'),
('Kasachstan','KZ','KAZ','398','KAZ','KZ','KZ','.kz'),
('Katar','QA','QAT','634','QAT','QA','Q','.qa'),
('Kenia','KE','KEN','404','KEN','KE','EAK','.ke'),
('Kirgisistan','KG','KGZ','417','KGZ','KG','KS','.kg'),
('Kiribati','KI','KIR','296','KIR','KR','KIR','.ki'),
('Kokosinseln','CC','CCK','166','','CK','','.cc'),
('Kolumbien','CO','COL','170','COL','CO','CO','.co'),
('Komoren','KM','COM','174','COM','CN','COM','.km'),
('Kosovo','XK','XKX','','KOS','KV','RKS','.ko'),
('Kroatien','HR','HRV','191','CRO','HR','HR','.hr'),
('Kuba','CU','CUB','192','CUB','CU','C','.cu'),
('Kuwait','KW','KWT','414','KUW','KU','KWT','.kw'),
('Laos','LA','LAO','418','LAO','LA','LAO','.la'),
('Lesotho','LS','LSO','426','LES','LT','LS','.ls'),
('Lettland','LV','LVA','428','LAT','LG','LV','.lv'),
('Libanon','LB','LBN','422','LBN','LE','RL','.lb'),
('Liberia','LR','LBR','430','LBR','LI','LB','.lr'),
('Libyen','LY','LBY','434','LBA','LY','LAR','.ly'),
('Liechtenstein','LI','LIE','438','LIE','LS','FL','.li'),
('Litauen','LT','LTU','440','LTU','LH','LT','.lt'),
('Luxemburg','LU','LUX','442','LUX','LU','L','.lu'),
('Macau','MO','MAC','446','','MC','','.mo'),
('Madagaskar','MG','MDG','450','MAD','MA','RM','.mg'),
('Malawi','MW','MWI','454','MAW','MI','MW','.mw'),
('Malaysia','MY','MYS','458','MAS','MY','MAL','.my'),
('Malediven','MV','MDV','462','MDV','MV','MV','.mv'),
('Mali','ML','MLI','466','MLI','ML','RMM','.ml'),
('Malta','MT','MLT','470','MLT','MT','M','.mt'),
('Marokko','MA','MAR','504','MAR','MO','MA','.ma'),
('Marshallinseln','MH','MHL','584','MHL','RM','MH','.mh'),
('Martinique','MQ','MTQ','474','','MB','','.mq'),
('Mauretanien','MR','MRT','478','MTN','MR','RIM','.mr'),
('Mauritius','MU','MUS','480','MRI','MP','MS','.mu'),
('Mayotte','YT','MYT','175','','MF','','.yt'),
('Mexiko','MX','MEX','484','MEX','MX','MEX','.mx'),
('Mikronesien','FM','FSM','583','FSM','FM','FSM','.fm'),
('Moldawien','MD','MDA','498','MDA','MD','MD','.md'),
('Monaco','MC','MCO','492','MON','MN','MC','.mc'),
('Mongolei','MN','MNG','496','MGL','MG','MGL','.mn'),
('Montenegro','ME','MNE','499','MNE','MJ','MNE','.me'),
('Montserrat','MS','MSR','500','','MH','','.ms'),
('Mosambik','MZ','MOZ','508','MOZ','MZ','MOC','.mz'),
('Myanmar','MM','MMR','104','MYA','BM','MYA','.mm'),
('Namibia','NA','NAM','516','NAM','WA','NAM','.na'),
('Nauru','NR','NRU','520','NRU','NR','NAU','.nr'),
('Nepal','NP','NPL','524','NEP','NP','NEP','.np'),
('Neukaledonien','NC','NCL','540','','NC','NCL','.nc'),
('Neuseeland','NZ','NZL','554','NZL','NZ','NZ','.nz'),
('Nicaragua','NI','NIC','558','NCA','NU','NIC','.ni'),
('Niederlande','NL','NLD','528','NED','NL','NL','.nl'),
('Niger','NE','NER','562','NIG','NG','RN','.ne'),
('Nigeria','NG','NGA','566','NGR','NI','NGR','.ng'),
('Niue','NU','NIU','570','','NE','','.nu'),
('Nordkorea','KP','PRK','408','PRK','KN','KP','.kp'),
('Nördliche Marianen','MP','MNP','580','','CQ','','.mp'),
('Nordmazedonien','MK','MKD','807','MKD','MK','MK','.mk'),
('Norfolkinsel','NF','NFK','574','','NF','','.nf'),
('Norwegen','NO','NOR','578','NOR','NO','N','.no'),
('Oman','OM','OMN','512','OMA','MU','OM','.om'),
('Österreich','AT','AUT','040','AUT','AU','A','.at'),
('Osttimor','TL','TLS','626','TLS','TT','TL','.tl'),
('Pakistan','PK','PAK','586','PAK','PK','PK','.pk'),
('Palästina','PS','PSE','275','PLE','WE','WB','.ps'),
('Palau','PW','PLW','585','PLW','PS','PAL','.pw'),
('Panama','PA','PAN','591','PAN','PM','PA','.pa'),
('Papua-Neuguinea','PG','PNG','598','PNG','PP','PNG','.pg'),
('Paraguay','PY','PRY','600','PAR','PA','PY','.py'),
('Peru','PE','PER','604','PER','PE','PE','.pe'),
('Philippinen','PH','PHL','608','PHI','RP','RP','.ph'),
('Pitcairninseln','PN','PCN','612','','PC','','.pn'),
('Polen','PL','POL','616','POL','PL','PL','.pl'),
('Portugal','PT','PRT','620','POR','PO','P','.pt'),
('Puerto Rico','PR','PRI','630','PUR','RQ','PRI','.pr'),
('Republik Kongo','CG','COG','178','CGO','CF','RCB','.cg'),
('Réunion','RE','REU','638','','RE','','.re'),
('Ruanda','RW','RWA','646','RWA','RW','RWA','.rw'),
('Rumänien','RO','ROU','642','ROU','RO','RUM','.ro'),
('Russland','RU','RUS','643','RUS','RS','RUS','.ru'),
('Saint Martin','MF','MAF','663','','RN','F','.mf'),
('Salomonen','SB','SLB','090','SOL','BP','SOL','.sb'),
('Sambia','ZM','ZMB','894','ZAM','ZA','Z','.zm'),
('Samoa','WS','WSM','882','SAM','WS','WS','.ws'),
('San Marino','SM','SMR','674','SMR','SM','RSM','.sm'),
('Sankt Bartholomäus','BL','BLM','652','','TB','','.bl'),
('São Tomé und Príncipe','ST','STP','678','STP','TP','STP','.st'),
('Saudi-Arabien','SA','SAU','682','KSA','SA','KSA','.sa'),
('Schweden','SE','SWE','752','SWE','SW','S','.se'),
('Schweiz','CH','CHE','756','SUI','SZ','CH','.ch'),
('Senegal','SN','SEN','686','SEN','SG','SN','.sn'),
('Serbien','RS','SRB','688','SRB','RI','SRB','.rs'),
('Seychellen','SC','SYC','690','SEY','SE','SY','.sc'),
('Sierra Leone','SL','SLE','694','SLE','SL','WAL','.sl'),
('Simbabwe','ZW','ZWE','716','ZIM','ZI','ZW','.zw'),
('Singapur','SG','SGP','702','SGP','SN','SGP','.sg'),
('Sint Maarten','SX','SXM','534','','NN','','.sx'),
('Slowakei','SK','SVK','703','SVK','LO','SK','.sk'),
('Slowenien','SI','SVN','705','SLO','SI','SLO','.si'),
('Somalia','SO','SOM','706','SOM','SO','SO','.so'),
('Spanien','ES','ESP','724','ESP','SP','E','.es'),
('Sri Lanka','LK','LKA','144','SRI','CE','CL','.lk'),
('St. Helena, Ascension und Tristan da Cunha','SH','SHN','654','','SH','','.sh'),
('St. Kitts und Nevis','KN','KNA','659','SKN','SC','KAN','.kn'),
('St. Lucia','LC','LCA','662','LCA','ST','WL','.lc'),
('St. Pierre und Miquelon','PM','SPM','666','','SB','','.pm'),
('St. Vincent und die Grenadinen','VC','VCT','670','VIN','VC','WV','.vc'),
('Südafrika','ZA','ZAF','710','RSA','SF','ZA','.za'),
('Sudan','SD','SDN','736','SUD','SU','SUD','.sd'),
('Südgeorgien und die Südlichen Sandwichinseln','GS','SGS','239','','SX','','.gs'),
('Südkorea','KR','KOR','410','KOR','KS','ROK','.kr'),
('Südsudan','SS','SSD','728','','','SSD','.ss'),
('Suriname','SR','SUR','740','SUR','NS','SME','.sr'),
('Svalbard und Jan Mayen','SJ','SJM','744','','SV','','.sj'),
('Syrien','SY','SYR','760','SYR','SY','SYR','.sy'),
('Tadschikistan','TJ','TJK','762','TJK','TI','TJ','.tj'),
('Taiwan','TW','TWN','158','TPE','TW','RC','.tw'),
('Tansania','TZ','TZA','834','TAN','TZ','EAT','.tz'),
('Thailand','TH','THA','764','THA','TH','T','.th'),
('Togo','TG','TGO','768','TOG','TO','TG','.tg'),
('Tokelau','TK','TKL','772','','TL','','.tk'),
('Tonga','TO','TON','776','TGA','TN','TON','.to'),
('Trinidad und Tobago','TT','TTO','780','TTO','TD','TT','.tt'),
('Tschad','TD','TCD','148','CHA','CD','TD','.td'),
('Tschechien','CZ','CZE','203','CZE','EZ','CZ','.cz'),
('Tunesien','TN','TUN','788','TUN','TS','TN','.tn'),
('Türkei','TR','TUR','792','TUR','TU','TR','.tr'),
('Turkmenistan','TM','TKM','795','TKM','TX','TM','.tm'),
('Turks und Caicosinseln','TC','TCA','796','','TK','','.tc'),
('Tuvalu','TV','TUV','798','TUV','TV','TUV','.tv'),
('Uganda','UG','UGA','800','UGA','UG','EAU','.ug'),
('Ukraine','UA','UKR','804','UKR','UP','UA','.ua'),
('Ungarn','HU','HUN','348','HUN','HU','H','.hu'),
('Uruguay','UY','URY','858','URU','UY','ROU','.uy'),
('Usbekistan','UZ','UZB','860','UZB','UZ','UZ','.uz'),
('Vanuatu','VU','VUT','548','VAN','NH','VAN','.vu'),
('Vatikanstadt','VA','VAT','336','','VT','V','.va'),
('Venezuela','VE','VEN','862','VEN','VE','YV','.ve'),
('Vereinigte Arabische Emirate','AE','ARE','784','UAE','AE','UAE','.ae'),
('Vereinigte Staaten von Amerika','US','USA','840','USA','US','USA','.us'),
('Vereinigtes Königreich','GB','GBR','826','GBR','UK','GBM','.uk'),
('Vietnam','VN','VNM','704','VIE','VM','VN','.vn'),
('Wallis und Futuna','WF','WLF','876','','WF','','.wf'),
('Weihnachtsinsel','CX','CXR','162','','KT','','.cx'),
('Westsahara','EH','ESH','732','','WI','WSA','.eh'),
('Zentralafrikanische Republik','CF','CAF','140','CAF','CT','RCA','.cf'),
('Zypern','CY','CYP','196','CYP','CY','CY','.cy')
;

ALTER TABLE Cities RENAME TO Cities_old;

CREATE TABLE Cities (
    ctyid INTEGER PRIMARY KEY,
    cityname TEXT NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    zeigeinvisu TEXT NOT NULL,
    firstadded INTEGER,
    request TEXT,
    active INTEGER NOT NULL,
    countrylinkage INTEGER,
    FOREIGN KEY (countrylinkage) REFERENCES Laendercodes (id)
);

INSERT INTO Cities (
    ctyid, 
    cityname, 
    lat, 
    lon,
    zeigeinvisu,
    firstadded,
    request,
    active
) 
SELECT 
    ctyid, 
    cityname, 
    lat, 
    lon,
    zeigeinvisu,
    firstadded,
    request,
    1
  FROM Cities_old
;

DROP TABLE IF EXISTS Cities_old;
